package com.four19ja.controllers;

import com.four19ja.repositories.LikeRepository;
import com.four19ja.entities.Like;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class LikeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LikeRepository likeRepository;

    @PostMapping(path = "/addLike") // Map ONLY POST Requests
    public @ResponseBody
    String addNewLike(@RequestParam Integer post, @RequestParam Integer user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Like l = new Like();
        l.setPost(post);
        l.setUser(user);
        likeRepository.save(l);
        return "Saved";
    }

    @GetMapping(path = "/allLike")
    public @ResponseBody Iterable<Like> getAllLike() {
        // This returns a JSON or XML with the users
        return likeRepository.findAll();
    }
}
